### ISSUE TITLE
Algorithm basis is unclear

### ISSUE THREAD

**Issue by 130s** [procrob/procrob_functional#4]
[README.md](https://github.com/procrob/face_recognition/blob/catkin/README.md):

```
All image processing and face recognition functionalities are provided by utilizing the Shervin Emami's c++ source code for face recognition (http://www.shervinemami.info/faceRecognition.html). 
```

But http://www.shervinemami.info/faceRecognition.html states:

```
This page was written in 2010 and describes Face Detection & Face Recognition using OpenCV's old C interface. But in June 2012, OpenCV v2.4.1 came with "FaceRecognizer" functionality. FaceRecognizer is much easier to use & understand than this old code. I have written a tutorial & free project using the new FaceRecognizer in Chapter 8 of the book "Mastering OpenCV". My new code also does better image preprocessing & rotation than the code on this page, but the book code doesn't have an offline recognition mode. You should read the official FaceRecognizer tutorials or use my new code instead of this page, and read Chapter 8 of the Mastering OpenCV book if you want to understand how it works.
```

which is unclear whether this ROS package is up to date or not.

**Comment by furushchev** [comment]
ping

**Comment by procrob** [comment]
Teaching face recognition or openCV is not the purpose of this package. It's for the ROS community to have an off-the-shelf face recognition module. If you are interested in details of how face recognition works, I suggest to follow the materials Shervin has suggested. If you are only interested to use the package, then test it and I would be happy to know your experience with its performance. I have plan to update this package with some new methods, but that might take some time.

**Comment by 130s** [comment]
No, my question above was NOT about general face recognition algorithm nor OpenCV. It was about how this package is implemented that wasn't unclear from the document I referred to.
