### ISSUE TITLE
[Question] Usage is unclear

### ISSUE THREAD

**Issue by 130s** [procrob/procrob_functional#5]
What steps exactly do I have to run in what order? 

I assumed the following, which doesn't seem to be working for me.
1. Publish `/camera/image_raw` I'm using shows clearly my face
2. `rosrun face_recognition Fserver`
3. `rosrun face_recognition Fclient`
4. `rostopic pub -1 /fr_order face_recognition/FRClientGoal -- 2 "your_name"` or other rostopic command that are mentioned in [README.md](https://github.com/procrob/face_recognition/blob/catkin/README.md).

Also, if successful, what result can I expect? In general, well-accepted ROS package description has "published topics" or similar section (e.g. http://wiki.ros.org/libuvc_camera#Published_Topics).

**Comment by 130s** [comment]
I seem to get something working, because with `rostopic pub -1 /fr_order face_recognition/FRClientGoal -- 0 "none"`I get a window pops up and on the `Fserver` terminal `Confidence is less than...` is printed. But it's still not clear from documentation what ROS developers can get from this result and how to utilize the returned info. Thanks!

**Comment by procrob** [comment]
Such questions should be asked in http://answers.ros.org

**Comment by 130s** [comment]
That makes sense. I opened [a question](http://answers.ros.org/question/217444/face_recognition-package-usage-is-unclear/). Thanks!
